### ISSUE TITLE
Aktivitätsbalken / Statusbalken hinzufügen

### ISSUE THREAD

**Issue by dompie** [EvolverDE/Signum-DEX#4]
Momentan gibt es kein visuelles Feedback in der Anwendung, das dem Nutzer den Zustand/Konnektivität der Anwendung vermittelt.

Daher wäre es gut, wenn es z.B. unten in der Statusleiste zwei Lämpchen geben könnte:
1. für "Synchronisationsstatus" mit der Blockchain:
    1. ROT: Unbekannt/Offline
    2. GELB: In Sync / Am Arbeiten
    3. GRÜN: Gesynced und Verbunden
2. Vielleicht irgendwie eine Art Integritätscheck/Einstellungscheck ob Daten ob alle Einstellungen und Dateien in Ordnung sind? Falls mal der PC abstürzt und es kaputte Dateien gibt.

**Comment by EvolverDE** [comment]
ist implementiert
